services:
  para_alias.command.add_alias_command:
    class: ParaAlias\Command\AddAliasCommand
    arguments:
      - '@para_alias.configuration.alias_configuration'
      - '@para_alias.factory.alias_factory'
    tags:
      - { name: console.command, command: 'alias:add' }

  para_alias.configuration.alias_configuration:
    class: ParaAlias\Configuration\AliasConfiguration
    arguments:
      - '@para.yaml.parser'
      - '@para.yaml.dumper'
      - '@para_alias.factory.alias_factory'
      - '%para.config%'
    calls:
      - [load]

  para.check_command_for_alias_subscriber:
    class: ParaAlias\EventSubscriber\CheckCommandForAliasSubscriber
    arguments: ['@para_alias.configuration.alias_configuration', '%para.config%']
    tags:
        - { name: 'kernel.event_subscriber' }

  para_alias.factory.alias_factory:
    class: ParaAlias\Factory\AliasFactory
